<?php

return [

    /*
    |--------------------------------------------------------------------------
    | 掃描股池
    |--------------------------------------------------------------------------
    |
    | 內建精選（台股權值 + 美股大型股）。Screener 掃描 = 本清單 ∪ 使用者
    | watchlist。可自行增減；新增後跑 php artisan screener:warm 預載價格。
    |
    */

    'universe' => [
        // 台股權值（依市值精選）
        ['symbol' => '2330.TW', 'name' => '台積電'],
        ['symbol' => '2317.TW', 'name' => '鴻海'],
        ['symbol' => '2454.TW', 'name' => '聯發科'],
        ['symbol' => '2412.TW', 'name' => '中華電'],
        ['symbol' => '2308.TW', 'name' => '台達電'],
        ['symbol' => '2303.TW', 'name' => '聯電'],
        ['symbol' => '2881.TW', 'name' => '富邦金'],
        ['symbol' => '2882.TW', 'name' => '國泰金'],
        ['symbol' => '2886.TW', 'name' => '兆豐金'],
        ['symbol' => '2891.TW', 'name' => '中信金'],
        ['symbol' => '2884.TW', 'name' => '玉山金'],
        ['symbol' => '2885.TW', 'name' => '元大金'],
        ['symbol' => '2892.TW', 'name' => '第一金'],
        ['symbol' => '2880.TW', 'name' => '華南金'],
        ['symbol' => '2883.TW', 'name' => '開發金'],
        ['symbol' => '2890.TW', 'name' => '永豐金'],
        ['symbol' => '2887.TW', 'name' => '台新金'],
        ['symbol' => '5880.TW', 'name' => '合庫金'],
        ['symbol' => '1301.TW', 'name' => '台塑'],
        ['symbol' => '1303.TW', 'name' => '南亞'],
        ['symbol' => '1326.TW', 'name' => '台化'],
        ['symbol' => '6505.TW', 'name' => '台塑化'],
        ['symbol' => '2002.TW', 'name' => '中鋼'],
        ['symbol' => '1101.TW', 'name' => '台泥'],
        ['symbol' => '1102.TW', 'name' => '亞泥'],
        ['symbol' => '2207.TW', 'name' => '和泰車'],
        ['symbol' => '2603.TW', 'name' => '長榮'],
        ['symbol' => '2609.TW', 'name' => '陽明'],
        ['symbol' => '2615.TW', 'name' => '萬海'],
        ['symbol' => '3711.TW', 'name' => '日月光投控'],
        ['symbol' => '2379.TW', 'name' => '瑞昱'],
        ['symbol' => '3034.TW', 'name' => '聯詠'],
        ['symbol' => '2357.TW', 'name' => '華碩'],
        ['symbol' => '2382.TW', 'name' => '廣達'],
        ['symbol' => '3008.TW', 'name' => '大立光'],
        ['symbol' => '2395.TW', 'name' => '研華'],
        ['symbol' => '4938.TW', 'name' => '和碩'],
        ['symbol' => '2408.TW', 'name' => '南亞科'],
        ['symbol' => '3231.TW', 'name' => '緯創'],
        ['symbol' => '2356.TW', 'name' => '英業達'],
        ['symbol' => '2324.TW', 'name' => '仁寶'],
        ['symbol' => '2345.TW', 'name' => '智邦'],
        ['symbol' => '6669.TW', 'name' => '緯穎'],
        ['symbol' => '3037.TW', 'name' => '欣興'],
        ['symbol' => '3045.TW', 'name' => '台灣大'],
        ['symbol' => '4904.TW', 'name' => '遠傳'],
        ['symbol' => '1216.TW', 'name' => '統一'],
        ['symbol' => '9910.TW', 'name' => '豐泰'],
        ['symbol' => '2801.TW', 'name' => '彰銀'],
        ['symbol' => '5871.TW', 'name' => '中租-KY'],
        // 美股大型
        ['symbol' => 'AAPL', 'name' => 'Apple'],
        ['symbol' => 'MSFT', 'name' => 'Microsoft'],
        ['symbol' => 'NVDA', 'name' => 'NVIDIA'],
        ['symbol' => 'GOOGL', 'name' => 'Alphabet'],
        ['symbol' => 'AMZN', 'name' => 'Amazon'],
        ['symbol' => 'META', 'name' => 'Meta'],
        ['symbol' => 'TSLA', 'name' => 'Tesla'],
        ['symbol' => 'AVGO', 'name' => 'Broadcom'],
        ['symbol' => 'JPM', 'name' => 'JPMorgan'],
        ['symbol' => 'V', 'name' => 'Visa'],
        ['symbol' => 'MA', 'name' => 'Mastercard'],
        ['symbol' => 'UNH', 'name' => 'UnitedHealth'],
        ['symbol' => 'XOM', 'name' => 'Exxon Mobil'],
        ['symbol' => 'LLY', 'name' => 'Eli Lilly'],
        ['symbol' => 'HD', 'name' => 'Home Depot'],
        ['symbol' => 'PG', 'name' => 'P&G'],
        ['symbol' => 'COST', 'name' => 'Costco'],
        ['symbol' => 'JNJ', 'name' => 'Johnson & Johnson'],
        ['symbol' => 'ORCL', 'name' => 'Oracle'],
        ['symbol' => 'ABBV', 'name' => 'AbbVie'],
        ['symbol' => 'BAC', 'name' => 'Bank of America'],
        ['symbol' => 'CRM', 'name' => 'Salesforce'],
        ['symbol' => 'CVX', 'name' => 'Chevron'],
        ['symbol' => 'KO', 'name' => 'Coca-Cola'],
        ['symbol' => 'AMD', 'name' => 'AMD'],
        ['symbol' => 'PEP', 'name' => 'PepsiCo'],
        ['symbol' => 'TMO', 'name' => 'Thermo Fisher'],
        ['symbol' => 'WMT', 'name' => 'Walmart'],
        ['symbol' => 'MCD', 'name' => "McDonald's"],
        ['symbol' => 'CSCO', 'name' => 'Cisco'],
        ['symbol' => 'ACN', 'name' => 'Accenture'],
        ['symbol' => 'ADBE', 'name' => 'Adobe'],
        ['symbol' => 'NFLX', 'name' => 'Netflix'],
        ['symbol' => 'LIN', 'name' => 'Linde'],
        ['symbol' => 'INTC', 'name' => 'Intel'],
        ['symbol' => 'QCOM', 'name' => 'Qualcomm'],
        ['symbol' => 'TXN', 'name' => 'Texas Instruments'],
        ['symbol' => 'AMAT', 'name' => 'Applied Materials'],
        ['symbol' => 'MU', 'name' => 'Micron'],
        ['symbol' => 'INTU', 'name' => 'Intuit'],
        ['symbol' => 'IBM', 'name' => 'IBM'],
        ['symbol' => 'CAT', 'name' => 'Caterpillar'],
        ['symbol' => 'GE', 'name' => 'GE Aerospace'],
        ['symbol' => 'DIS', 'name' => 'Disney'],
        ['symbol' => 'VZ', 'name' => 'Verizon'],
        ['symbol' => 'PLTR', 'name' => 'Palantir'],
        ['symbol' => 'ANET', 'name' => 'Arista Networks'],
        ['symbol' => 'NOW', 'name' => 'ServiceNow'],
        ['symbol' => 'UBER', 'name' => 'Uber'],
        ['symbol' => 'QQQ', 'name' => 'Invesco QQQ ETF'],
    ],

    'history_days' => 250,

    'scan_time_budget_seconds' => 60,

];
